openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/v2"

components:
  schemas:
    VirtualNetwork:
      type: "object"
      required:
        - "name"
        - "network"
      properties:
        name:
          type: "string"
        mode:
          type: "integer"
          description: "nat, route, open, bridge, private, passthrough, hostdev, vepa, "
        network:
          type: "string"
        tag:
          type: "array"

paths:
  /virtualnetwork:
    post:
      operationId: "APIS.VirtualNetwork.main.add_virtualnetwork"
      tags:
        - "virtualnetwork"
      summary: "Create a new virtual network"
      requestBody:
        description: "Virtual Network to be created"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VirtualNetwork"
      responses:
        "200":
          description: "Successfully creation of Virtual Network"
    get:
      operationId: "APIS.VirtualNetwork.main.list_virtualnetwork"
      tags:
        - "virtualnetwork"
      summary: "List all my Virtual Network"
      responses:
        "200":
          description: "Successfully list my Virtual Network"
  /virtualnetwork/{name}:
    get:
      operationId: "APIS.VirtualNetwork.main.get_virtualnetwork"
      tags:
        - "virtualnetwork"
      summary: "Get a Virtual Network"
      parameters:
        - name: "name"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Successfully get a Virtual Network"